CREATE TABLE [dbo].[Person]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [FName] NVARCHAR(50) NOT NULL, 
    [LName] NVARCHAR(50) NOT NULL, 
    [Email] NVARCHAR(100) NOT NULL, 
    [Phone] INT NOT NULL, 
    [Dob] DATETIME NULL, 
)
